name: Snapcraft Builds

on:
    push:
        branches:
            - release
    workflow_dispatch:

jobs:
  build-snapcraft:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: setup node
      uses: actions/setup-node@v4
      with:
          node-version: lts/*
          #cache: 'npm'
    
    - name: Installs shelljs
      run: npm i shelljs

    - name: Adds env vars to Snapcraft
      env:
        BRANDFETCH_USER_ID: ${{ secrets.BRANDFETCH_USER_ID }}
      run: sed -i -e "s/{{BRANDFETCH_USER_ID}}/$BRANDFETCH_USER_ID/g" ./snapcraft.yaml

    - name: Build Snap package
      uses: snapcore/action-build@v1
      id: build
    
    - name: Publish to snap store
      uses: snapcore/action-publish@v1
      env:
        SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_TOKEN }}
      with:
        snap: ${{ steps.build.outputs.snap }}
        release: edge
